version: '3.8'

services:
  # Servizio Database (PostgreSQL) - COMMENTATO PER USARE DB LOCALE
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: bugboard_postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${DB_USER:-admin}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
  #     POSTGRES_DB: ${DB_NAME:-bugboard}
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - bugboard_network

  # Servizio Backend (Node.js/Express)
  backend:
    build: ./backend
    container_name: bugboard_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      PORT: 3000
      # PUNTA AL PC LOCALE ("HOST") INVECE CHE AL CONTAINER "postgres"
      DB_HOST: host.docker.internal 
      DB_PORT: 5432
      # Usiamo direttamente le credenziali del tuo .env locale
      DB_USER: postgres
      DB_PASSWORD: francy09
      DB_NAME: IngSW
      DB_DIALECT: postgres
    # Aggiunta fondamentale per Linux per risolvere 'host.docker.internal'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   - postgres
    networks:
      - bugboard_network

  # Servizio Frontend (Flutter Web servito da Nginx)
  frontend:
    build: ./bugboard_frontend
    container_name: bugboard_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - bugboard_network

volumes:
  postgres_data:

networks:
  bugboard_network:
    driver: bridge